name: MERN CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    # - name: Run backend tests
    #   run: |
    #     cd backend
    #     npm test

    - name: Install frontend dependencies
      run: |
        cd front
        npm install

    - name: Build frontend
      run: |
        cd front
        npm run build
